### ISSUE TITLE
Does not seem to work with RN 0.56

### ISSUE THREAD

**Issue by adrienthiery** [juddey/ignite-react-native-navigation#5]
Hi there,

This issue is a bit of straight thought sharing, and maybe a bit of useful bug reporting 😅 

Wanted to try out RNN v2, but I went through 3 errors while trying the plugin:
* `Error: Cannot find module 'fs-jetpack'` (solved by `yarn add -D fs-jetpack`)
* `Error: Cannot find module 'ramda'` (solved by `yarn add -D ramda`)
* `✖ 'implementation "com.android.support:appcompat-v7:25.4.0"' was not found in file MyProject/android/app/build.gradle.`

I guess 'cause RN 0.56 uses now the `ext` variables for versions (I got `compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"`).

Another problem to solve is that RN 0.56 does not come with gradle 3 support.

So we're stuck between using 0.57 with gradle 3 out of the box, but not supported by RNN (does using `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative56"` with 0.57 work? 🤔 ) or handling the gradle upgrade in `ignite-react-native-navigation` for 0.56?

**Comment by juddey** [comment]
Hey, thanks - I'm knee deep in a web js project right now, so haven't been RN'ing. Should be back to RN in a couple of weeks, and will look at this then.

**Comment by juddey** [comment]
I've just been having a look at this today and I'm thinking to go ahead with the upgrade to .57.4 to see how it pans out. It'll remove the gradle upgrade from my scripts (which I like) and it looks like there are some already using .57 with success.  

This is interesting: https://github.com/wix/react-native-navigation/pull/3851#issuecomment-430900865

I don't plan to use react components in the topbar (yet!) - by the time I get there .58 probz would have landed and so things might be more rosy. Anyway, Its worth a shot and I'll post back here how it goes.

cc @jamonholmgren for interests sake

**Comment by juddey** [comment]
So here it is, with 57.4: 

![image](https://user-images.githubusercontent.com/7445602/48107969-47b08780-e2a6-11e8-95fb-527c4dd78ff6.png)

Only had to remove this line from MainApplication.java for things to compile:
`import com.facebook.react.uimanager.UIImplementationProvider;`

which all makes sense when you read the comments on the issue above. I'm gonna run with it for a few days and see what comes. :wave:

**Comment by adrienthiery** [comment]
Nice! Good job :) still open for merging all of that in ignite-native-navigation when you want :)
